//dropdown items
export const items = [
  {
    title: "Most Relevant",
    option: ["Most Recent", "Highest Pay"],
  },
  {
    title: "Date Posted",
    option: ["Today", "1-3 Days", "1-7 Days"],
  },
  {
    title: "Job Type",
    option: ["Hourly", "Fixed Price"],
  },
  {
    title: "Category",
    option: [
      "Front-End Development",
      "Back-End Development",
      "Full Stack Development",
      "Product Management",
      "Product Marketing",
      "Project Management",
    ],
  },
  {
    title: "Skills",
    option: [
      "Adobe",
      "Amazon Web Services (AWS)",
      "Android Development",
      "Angular",
      "Apache HTTP Server",
      "API",
      "Bootstrap",
      "C",
      "C++",
      "CSS",
      "C Sharp",
      "Django",
      "Flask",
      "Flutter",
      "Graphic Design",
      "GO",
      "HTML",
      "iOS Development",
      "Java",
      "Javascript",
      "jQuery",
      "Kubernetes",
      "Mobile App Development",
      "MySQL",
      "Node.js",
      "NoSQL",
      "PHP",
      "PostgreSQL",
      "Python",
      "React",
      "React Native",
      "Redis",
      "Redux",
      "RESTful",
      "Ruby",
      "Saas",
      "Shopify",
      "TypeScript",
      "UX/UI",
      "Vue.js",
      "Web Design",
      "WordPress"
    ],
  },
  {
    title: "Salary",
    option: [""],
  },
  {
    title: "Location",
    option: [
      "United States",
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "District of Columbia",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
];
